name: Brian Test Site
favicon: null
layout_spectrum: 0.6348777634557337
typography_spectrum: 0.1502
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.14902216754853725
  lightness: 0.07430946477688849
  saturation: 0.6349025720264763
  rhythmicContrast: 0.3235754615161568
purpose: []
